name: sync theme submodules

on:
  push:
    branches: gh-pages

  schedule:
     - cron: "00 14 * * *"

  workflow_dispatch: null


jobs:
  sync_theme_submodules:
    if: github.repository_owner == 'ioos' # only run if ioos owns repo
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      with: { ref: gh-pages }

    - name: submodule checkout
      run: |
           git submodule update --init
    - name: check submodule status
      run: |
          git submodule status
    - name: Update theme from submodules
      run: |
           git submodule update --remote --merge
    - name: check submodule status 2
      run: |
           git submodule status
    - name: Commit and push if it changed
      run: |
           git config user.name "Automated"
           git config user.email "actions@users.noreply.github.com"
           git add -A
           timestamp=$(date -u)
           git commit -m "Update theme on: ${timestamp}" || exit 0
           git push

  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - uses: gautamkrishnar/keepalive-workflow@75c59336a3a6589777ab715d83668bb3033c68b2 # 2.0.9
